stages:
- build

container_build:
    image: quay.io/podman/stable
    stage: build
    services:
        - docker:dind
    before_script:
        - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - podman build --pull -t $CI_REGISTRY_IMAGE/shiny_app:$CI_COMMIT_BRANCH -f dockerfile .
        - podman tag $CI_REGISTRY_IMAGE/shiny_app:$CI_COMMIT_BRANCH $CI_REGISTRY_IMAGE/shiny_app:$CI_COMMIT_SHORT_SHA
        - podman push $CI_REGISTRY_IMAGE/shiny_app:$CI_COMMIT_BRANCH
        - podman push $CI_REGISTRY_IMAGE/shiny_app:$CI_COMMIT_SHORT_SHA
    rules:
      - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop" 
        changes:
          - dockerfile
        when: on_success
        allow_failure: true
      # Give the option to run the job manually as needed
      - when: manual
        allow_failure: true
