default:
  golem_name: kestermadnr
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: /home/rstudio/project-analytics-files/workspace/kester-smith-wahl-march-madness/kesterMadnr
